# Проект для локальной отладки в контейнере
# Собирает образ приложения на базе текущего состояния рабочей директории и запускает систему целиком

version: '3'

services:

  app:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/qyoga
      - SPRING_PROFILES_ACTIVE=prod,demo

    build:
      context: ../../
      dockerfile: deploy/qyoga/Dockerfile

    depends_on:
      - postgres
    ports:
      - "8080:8080"
    links:
      - "postgres:database"